common:
  prefix:
    /api/o11y/insight
  DB:
    URL: mc-observability-maria
    USERNAME: mc-agent
    PASSWORD: mc-agent
    DATABASE: mc_observability
  InfluxDB:
    HOST: mc-observability-influx
    PORT: 8086
    USERNAME: mc-agent
    PASSWORD: mc-agent
    DATABASE: insight
    POLICY: autogen
  MC-O11Y:
    URL: mc-observability-manager
    PORT: 18080

anomaly:
  target_types:
    types:
      - vm
      - mci
  measurements:
    types:
      - cpu
      - mem
  measurement_fields:
    - measurement: cpu
      fields:
        - field_key: usage_idle
          unit: percent
    - measurement: mem
      fields:
        - field_key: used_percent
          unit: percent
  execution_intervals:
    intervals:
      - 5m
      - 10m
      - 30m
  rrcf:
    num_trees: 10
    shingle_ratio: 0.01
    tree_size: 1024
    anomaly_range_size: 2.5

prediction:
  target_types:
    types:
      - vm
      - mci
  measurements:
    types:
      - cpu
      - mem
      - disk
      - system
  measurement_fields:
    - measurement: cpu
      fields:
        - field_key: usage_idle
          unit: percent
    - measurement: disk
      fields:
        - field_key: used_percent
          unit: percent
    - measurement: mem
      fields:
        - field_key: used_percent
          unit: percent
    - measurement: system
      fields:
        - field_key: load1
          unit: percent

  prediction_ranges:
    min: 1h
    max: 2160h
  prediction_history:
    default_range: 168
  prophet:
    PROPHET_CPS: 10.0
    PROPHET_SPS: 10.0
    PROPHET_HPS: 0.05
    PROPHET_SM: additive
    REMOVE_COLUMNS:
      - trend
      - yhat_lower
      - yhat_upper
      - trend_lower
      - trend_upper
      - additive_terms
      - additive_terms_lower
      - additive_terms_upper
      - daily
      - daily_lower
      - daily_upper
      - weekly
      - weekly_lower
      - weekly_upper
      - multiplicative_terms
      - multiplicative_terms_lower
      - multiplicative_terms_upper

log_analysis:
  model:
    - provider: ollama
      model_name:
        - llama3.1:8b
        - mistral:7b
    - provider: openai
      model_name:
        - gpt-4o
        - gpt-4o-mini
        - gpt-3.5-turbo
  mcp:
    mcp_grafana_url: http://mc-observability-mcp-grafana:8000/sse
    system_prompt_first: |
      <system_prompt>
      You are an agent - System Log Investigator.
      You MUST search MariaDB: mc_observability -> mc_o11y_trigger_history, InfluxDB: mc-observability DB. Do NOT search any others.
      Your primary directive is to base all findings strictly on real data retrieved via the InfluxDB MCP tools. You MUST first generate an InfluxQL query and analyze the actual data returned. You are strictly forbidden from inventing data, assuming data exists without verification, or providing speculative answers like "the data might look like this." Such actions would critically undermine the reliability of the management system.

      Your Mission:

      1. Anomaly Detection: Identify and describe any abnormal patterns in the data (e.g., sudden spikes, sustained threshold breaches).
      2. Potential Cause Analysis: Based on the detected anomaly, speculate on 2-3 potential causes.
      3. Actionable Recommendations: Suggest clear, step-by-step action items for a developer to immediately check or execute.

      Your response MUST be structured into the following three distinct sections: 'Analysis Result', 'Potential Causes', and 'Actionable Recommendations'.
      This entire process must be adhered to with absolute rigor, regardless of the input data or circumstances. This is the only way to ensure a successful and reliable system log investigation.
      </system_prompt>

      <mcp_introduction>
      You can use MariaDB, InfluxDB MCP.
      You must use each tool appropriately for the given situation. All tools listed here are verified and can be used freely at any time. The use of MCP tools is strongly encouraged, and you are required to return the output values correctly.
      MariaDB's mc_o11y_trigger_history has data related to alarm history. We need to check this data first to know what happened, and we need to analyze InfluxDB's mc-observability DB based on this data.
      </mcp_introduction>
      </system_prompt>
      
      Time: {current_time}
  system_prompt_default: |
    MC-Observability 플랫폼의 AI 어시스턴트로서 계속 대화를 이어가겠습니다.
    시계열 데이터와 관계형 데이터를 활용하여 정확한 분석과 인사이트를 제공하겠습니다.
    
    현재 시간: {current_time}